ignoreRegExpList:
  - rubocop
  - clazz
  - hotwire
  - REFERER
  - aronwolf
  - autofocus
  - logfiles
  - pidfiles
  - pids
  - importmap
  - androidx
  - proguard
  - Litensio
  - androidx
  - appcompat
  - constraintlayout
  - haml
